<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[5]=array(0,1,1,'5ri45oiP5paw6Ze7');
$cfg_Cs[6]=array(0,1,0,'57K+5ZOB5ri45oiP');
$cfg_Cs[7]=array(0,1,1,'6K+E5rWL5pS755Wl');
$cfg_Cs[8]=array(0,1,0,'5LiT6aKY5ZCI6ZuG');
$cfg_Cs[9]=array(0,1,0,'5bCP57yW5o6o6I2Q');
$cfg_Cs[10]=array(0,2,0,'5ri45oiP5oiq5Zu+');
$cfg_Cs[11]=array(0,14,0,'5ri45oiP6KeG6aKR');
$cfg_Cs[12]=array(0,13,0,'5ri45oiP5bqT');
$cfg_Cs[13]=array(0,1,0,'6aaW6aG1');
$cfg_Cs[14]=array(13,1,0,'6L2u5pKt56qX');
?>